//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int id { get; set; }
        public int WeekId { get; set; }
        public int Rink { get; set; }
        public int TeamNo1 { get; set; }
        public Nullable<int> TeamNo2 { get; set; }
        public int Team1Score { get; set; }
        public int Team2Score { get; set; }
        public byte[] rowversion { get; set; }
        public int ForFeitId { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
