//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RinkOrder
    {
        public int id { get; set; }
        public string Green { get; set; }
        public string Direction { get; set; }
        public string Boundary { get; set; }
        public byte[] rowversion { get; set; }
    }
}
