//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeague
    {
        public int id { get; set; }
        public int UserId { get; set; }
        public int LeagueId { get; set; }
        public string Roles { get; set; }
        public byte[] rowversion { get; set; }
    
        public virtual League League { get; set; }
        public virtual User User { get; set; }
    }
}
