//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeagueView
    {
        public int id { get; set; }
        public string LeagueName { get; set; }
        public string username { get; set; }
        public string league_role { get; set; }
        public string site_role { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
